### ISSUE TITLE
xrp prices 

### ISSUE THREAD

**Issue by togonow** [css459/cryptick#3]
just wandering about xrp pricing. Which market exchange? Thanks

**Comment by css459** [comment]
Hi togonow,

The price for XRP is from CoinMarketCap, since I believe it is the most true market price for the currency. In fact, I plan to transfer the prices for Bitcoin and Ethereum over to CoinMarketCap as well since I think listing the price for one exchange yields an inaccurate price.

The project was originally a personal project, but I think now it can be better abstracted to more people and more coins, and that means moving away from GDAX prices.
